### ISSUE TITLE
If I didn't select dates of my trip on start screen I cannot add a place while editing the trip

### ISSUE THREAD

**Issue by Kirunia** [dudluk/TravelPlanner#12]
Maybe the trip should ask me when do I want to go to that place? Or add today's date as a starting date and a possibility to edit the date range.

**Comment by Kirunia** [comment]
If only one day added to the trip, I cannot add more places. Maybe adding another place should extend the dates range by 1 additional day.

**Comment by dudluk** [comment]
Fixed
